name: too_good_to_go
description: Too Good To Go
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Packages.
  cupertino_icons: ^1.0.3
  get: ^4.1.4
  url_launcher: ^6.0.6
  google_maps_flutter: ^2.0.6
  location: ^4.2.2
  dotted_border: ^2.0.0
  flutter_spinkit: ^5.0.0
  animated_splash_screen: ^1.1.0
  flutter_speed_dial: ^3.0.5
  ####
  http: ^0.13.3
  get_it: ^6.1.1
  provider: ^4.3.3
  data_connection_checker: ^0.3.4
  modal_progress_hud: ^0.1.3
  share: ^2.0.1
  shared_preferences: ^2.0.6
  hive: ^2.0.4
  shimmer: ^2.0.0
  auto_size_text: ^2.1.0
  cached_network_image: ^3.0.0
  injectable: ^1.3.0
  like_button: ^2.0.0
  intl: ^0.17.0
  email_validator: ^2.0.1
  flutter_html: ^1.3.0
  geolocator: ^7.1.1
  build_runner: ^2.0.5

dev_dependencies:
  #flutter_launcher_name: any
  #change_app_package_name: ^1.0.0
  #flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter

#flutter_launcher_name:
  #name: "Too Good To Go"


flutter_icons:
  android: "app_icon_round"
  ios: true
  image_path: "images/app_icon_round.png"

flutter:
  uses-material-design: true
  assets:
    - images/
    - icons/